export const environment = {
  production: true,
  idClient: 0,
  name: '',
  token: '',
  type_user: '',
  idProduct: 0,
  title: '',
  description: '',
  price: 0,
  author: '',
  year: 0,
  inventory: 0,
  language: '',
  isbn: 0,
  ean: 0,
  country: '',
  publisher: '',
  format: '',
  pages: 0,
  photo: '',
  quantity: 0,
  partialValue: 0,
};
